env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended
  - plugin:import/warnings

parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: module

rules:
  semi: error
  no-shadow: error

ignorePatterns:
  - packages/site/src/js/ga.js
