language: node_js

node_js:
  - "12"

cache:
  yarn: true
  directories:
    - node_modules

# Make chrome browser available for testing
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

# Services are not supported on osx...
# services:
#   - xvfb

install:
  - yarn

addons:
  # chrome: stable # not needed if Saucelabs is used
  sauce_connect:
    direct_domains: "*.vimeo.com"

jobs:
  include:
    - stage: Tests
      name: "Unit tests"
      script:
        - hostname -I
        - COVERAGE=true yarn test --single-run --console --stack

after_success:
  - yarn run coverage
