sudo: true
os: osx
language: node_js
node_js:
  - "13"
cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

jobs:
  include:
    - stage: Tests
      name: "Unit tests"
      script: COVERAGE=true yarn test --single-run --console --stack

after_success:
  - yarn run coverage
