sudo: true
language: node_js
node_js:
  - "13"
cache:
  yarn: true
  directories:
    - node_modules

services:
  - xvfb

addons:
  chrome: stable
  # sauce_connect: true

script:
  - COVERAGE=true yarn test --single-run --console --stack --log-level debug

after_success:
  - yarn run coverage
