sudo: true
language: node_js
node_js:
  - "13"
cache:
  yarn: true
  directories:
    - node_modules

services:
  - xvfb

addons:
  chrome: stable

jobs:
  include:
    - stage: Tests
      name: "Unit tests"
      script: COVERAGE=true yarn test --single-run --console --stack
    - script: yarn bench
      name: "Benchmark"

after_success:
  - yarn run coverage
