sudo: true
language: node_js
node_js:
  - "13"

services:
  - xvfb

addons:
  chrome: stable
  # sauce_connect: true

script:
  - COVERAGE=true yarn test --single-run --stack --log-level debug

after_success:
  - yarn run coverage
