
url: https://dev.playerx.io
apiUrl: https://api.playerx.io
oEmbedUrl: https://api.playerx.io
githubUrl: https://github.com/luwes/playerx
defaultPlayerSrc: https://vimeo.com/648359100
defaultIframeSrc: https://player.vimeo.com/video/648359100
