
url: https://dev.playerx.io
apiUrl: https://api.playerx.io
oEmbedUrl: https://api.playerx.io
githubUrl: https://github.com/playerxo/playerx
defaultPlayerSrc: https://vimeo.com/638369396
defaultIframeSrc: https://player.vimeo.com/video/638369396
