# This is a basic workflow to help you get started with Actions

name: Cloudflare Site Deploy

# Controls when the action will run.
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # deploy every 2 hours to update the MUX stats
    - cron: '0 */2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run Cloudflare deploy
      uses: fjogeleit/http-request-action@master
      with:
        url: ${{ secrets.CLOUDFLAR_DEPLOY_HOOK_URL }}
        method: 'POST'
