name: Lighthouse CI
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          configPath: ./lighthouserc.js
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
        env:
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
