name: Lighthouse CI
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # deploy every 3 hours to update the MUX stats
    - cron: '0 */3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          configPath: ./lighthouserc.js
          uploadArtifacts: true # save results as an action artifacts
          serverBaseUrl: https://lhci.playerx.io
          serverToken: ${{ secrets.LHCI_TOKEN }}
        env:
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
